export const CONFIG = {
  EXAM_TITLE: '对外汉语初级期末听力考试',
  EXAM_MINUTES: 60,
  ANSWER_SECONDS: 5,
  GAP_BETWEEN_PLAYS_MS: 700,
  GAP_BETWEEN_QUESTIONS_MS: 500,
  GOOGLE_APPS_SCRIPT_URL: 'PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE',
  STORAGE_KEY: 'pkru-listening-final-v1',
  VERSION: '1.0.0'
};
